name: Build NullOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm xorriso grub-pc-bin grub-common

      - name: Ensure required directories exist
        run: mkdir -p build/x86_64 dist/x86_64 targets/x86_64/iso/boot

      - name: Compile Assembly Files
        run: make build-x86_64

      - name: Create Bootable ISO
        run: |
          cp dist/x86_64/kernel.bin targets/x86_64/iso/boot/kernel.bin
          grub-mkrescue -o dist/x86_64/kernel.iso targets/x86_64/iso

      - name: Upload Kernel Binary (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: NullOS-Kernel
          path: dist/x86_64/kernel.bin

      - name: Upload ISO Image (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: NullOS-ISO
          path: dist/x86_64/kernel.iso
