name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y nasm x86_64-elf-binutils x86_64-elf-gcc grub-pc-bin grub-common qemu-system-x86

    - name: Build Kernel
      run: make build-x86_64

    - name: Verify Kernel ISO
      run: ls -lh dist/x86_64/kernel.iso

    # Optional: Run the kernel in QEMU for automated testing
    # - name: Test Kernel in QEMU
    #   run: qemu-system-x86_64 -cdrom dist/x86_64/kernel.iso -nographic -no-reboot -serial stdio
